from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DomainSpec:
    id: str
    title: str
    flemings_alignment: tuple[str, ...]
    min_sources: int
    queries: tuple[str, ...]
    target_fields: tuple[str, ...]


DOMAINS: dict[str, DomainSpec] = {
    "D1": DomainSpec(
        id="D1",
        title="Alloy Systems & Solidification Processing Routes",
        flemings_alignment=("Processing routes", "Ch.1 heat and solute conservation"),
        min_sources=15,
        queries=(
            "metal alloy solidification microgravity space",
            "ISS solidification experiment alloy",
            "TEMPUS ESA microgravity solidification",
            "sounding rocket solidification Al Cu",
            "parabolic flight metallic alloy solidification",
            "FOTON satellite solidification experiment",
            "TEXUS microgravity solidification",
            "electromagnetic levitation space EML",
            "Bridgman solidification space shuttle",
        ),
        target_fields=(
            "alloy_system",
            "composition",
            "platform",
            "facility",
            "solidification_technique",
            "cooling_rate_K_per_s",
            "G_K_per_m",
            "V_um_per_s",
            "G_over_V",
            "sample_geometry",
            "microgravity_duration",
            "experiment_year",
            "mission",
        ),
    ),
    "D2": DomainSpec(
        id="D2",
        title="Fluid Flow, Convection, and Macrosegregation",
        flemings_alignment=("Ch.1 heat and solute conservation", "Ch.7 macrosegregation theory"),
        min_sources=12,
        queries=(
            "macrosegregation microgravity solidification suppressed convection",
            "Marangoni convection solidification space",
            "solutal convection microgravity metal alloy",
            "thermosolutal convection reduced gravity solidification",
            "buoyancy-driven flow suppression space alloy",
            "microsegregation vs macrosegregation microgravity",
            "Flemings segregation microgravity comparison",
            "channel segregation freckles microgravity",
            "Al-Cu macrosegregation 1g microgravity comparison",
        ),
        target_fields=("segregation_coefficient_k", "macrosegregation_index", "convection_velocity_m_per_s", "Ma", "Ra", "Gr"),
    ),
    "D3": DomainSpec(
        id="D3",
        title="Dendritic and Cellular Solidification",
        flemings_alignment=("Ch.3 dendrite spacing", "Ch.5 growth kinetics"),
        min_sources=15,
        queries=(
            "dendritic solidification microgravity primary arm spacing",
            "PDAS SDAS microgravity comparison 1g",
            "cellular dendrite transition microgravity",
            "dendrite tip radius microgravity",
            "dendrite growth velocity undercooling microgravity",
            "Al-Cu dendrite ISS DECLIC experiment",
            "DECLIC-DSI dendrite solidification",
            "succinonitrile dendrite microgravity transparent analog",
            "columnar to equiaxed transition microgravity CET",
            "spacing selection microgravity solidification",
        ),
        target_fields=("lambda1_um", "lambda2_um", "dendrite_tip_radius_um", "dendrite_tip_velocity_um_per_s", "undercooling_K"),
    ),
    "D4": DomainSpec(
        id="D4",
        title="Eutectic, Peritectic, Polyphase & Immiscible Systems",
        flemings_alignment=("Ch.4 eutectic growth", "Ch.6 polyphase reactions"),
        min_sources=12,
        queries=(
            "eutectic solidification microgravity lamellar spacing",
            "Al-Si eutectic microgravity ISS",
            "monotectic alloy microgravity phase separation",
            "immiscible alloy microgravity droplet coarsening",
            "peritectic solidification reduced gravity",
            "Al-Bi Al-Pb immiscible microgravity",
            "hypermonotectic solidification space",
            "eutectic spacing prediction microgravity Jackson-Hunt",
            "polyphase solidification convection suppression space",
            "FOTON monotectic experiment",
        ),
        target_fields=("phase_type", "lamellar_spacing_um", "phase_morphology", "droplet_size_um", "coarsening_rate_um3_per_s"),
    ),
    "D5": DomainSpec(
        id="D5",
        title="Nucleation, Undercooling, and Interface Kinetics",
        flemings_alignment=("Ch.9 nucleation", "Ch.9 interface kinetics"),
        min_sources=12,
        queries=(
            "nucleation undercooling microgravity containerless processing",
            "maximum undercooling space electromagnetic levitation",
            "heterogeneous nucleation suppression microgravity",
            "TEMPUS ISS undercooling metallic melt",
            "EML-ISS undercooling nucleation",
            "bulk undercooling Ni Fe space",
            "crystal nucleation kinetics microgravity",
            "nucleation rate reduced gravity",
            "interface kinetics solidification front space",
            "metastable phase nucleation microgravity",
        ),
        target_fields=("maximum_undercooling_K", "nucleation_temperature_K", "nucleation_mechanism", "nucleation_rate_m3_s", "interface_velocity_m_per_s"),
    ),
    "D6": DomainSpec(
        id="D6",
        title="Thermophysical Properties, Heat Flow & Plane-Front Solidification",
        flemings_alignment=("Ch.1 heat flow", "Ch.2 plane fronts", "Ch.8 stability"),
        min_sources=12,
        queries=(
            "thermophysical properties metallic melt microgravity measurement",
            "thermal conductivity viscosity surface tension space measurement",
            "specific heat metallic melt electromagnetic levitation ISS",
            "TEMPUS thermophysical property measurement",
            "plane front solidification stability microgravity",
            "constitutional supercooling microgravity",
            "Mullins-Sekerka instability microgravity experiment",
            "thermal diffusivity metallic melt space",
            "density metallic melt microgravity",
            "solidification front stability reduced gravity",
        ),
        target_fields=("thermal_conductivity_W_mK", "specific_heat_J_kgK", "density_kg_m3", "viscosity_mPa_s", "surface_tension_N_m"),
    ),
    "D7": DomainSpec(
        id="D7",
        title="Detached Bridgman and Semiconductor Crystal Quality",
        flemings_alignment=("Ch.2 directional solidification", "Ch.9 interface kinetics"),
        min_sources=12,
        queries=(
            "detached Bridgman microgravity semiconductor crystal",
            "Bridgman gap formation microgravity GaAs InSb",
            "space crystal growth dislocation density microgravity",
            "vapour pressure controlled Bridgman space",
            "CdTe Ge Bridgman microgravity crystal quality",
            "etch pit density microgravity Bridgman crystal",
            "dewetting solidification microgravity contact angle",
            "MEPHISTO Bridgman space shuttle",
            "crystal quality comparison ground flight Bridgman",
            "rocking curve XRD microgravity crystal",
        ),
        target_fields=("growth_rate_mm_h", "thermal_gradient_K_cm", "gap_width_um", "contact_angle_deg", "etch_pit_density_cm2"),
    ),
    "D8": DomainSpec(
        id="D8",
        title="Gas Porosity, Bubble Behaviour & Additive Manufacturing Bridge",
        flemings_alignment=("Ch.10 defects", "Additive manufacturing bridge"),
        min_sources=20,
        queries=(
            "gas porosity solidification microgravity bubble",
            "hydrogen porosity aluminium microgravity",
            "bubble migration Marangoni convection space",
            "porosity formation reduced gravity casting",
            "shrinkage porosity microgravity solidification",
            "keyhole porosity additive manufacturing melt pool",
            "melt pool convection LPBF Marangoni flow",
            "gas pore formation selective laser melting",
            "rapid solidification additive manufacturing dendrite",
            "keyhole dynamics vapour pressure melt pool",
        ),
        target_fields=("pore_volume_fraction_pct", "mean_pore_diameter_um", "bubble_rise_velocity_m_per_s", "AM_process", "pore_type"),
    ),
    "D9": DomainSpec(
        id="D9",
        title="Processing-Structure-Property & Mechanical Data",
        flemings_alignment=("Ch.10 properties and defects",),
        min_sources=12,
        queries=(
            "mechanical properties microgravity solidified alloy",
            "tensile strength yield stress microgravity cast alloy",
            "hardness microstructure microgravity solidification",
            "fatigue properties space solidified specimen",
            "creep microgravity solidified superalloy",
            "Al-Cu Al-Si mechanical properties microgravity",
            "grain size mechanical properties reduced gravity",
            "Hall-Petch microgravity solidification",
            "processing structure property microgravity persistent gap",
            "space manufacturing mechanical performance",
        ),
        target_fields=("grain_size_um", "yield_strength_MPa", "UTS_MPa", "elongation_pct", "hardness", "fatigue_limit_MPa"),
    ),
}

